/// <reference types="vite/client" />
import { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

type Status = 'new' | 'ready' | 'needs_info' | 'referred';
type Summary = { id: string; insured: string; broker: string; status: Status; priority: string; tiv: number | null; requested_limit: number | null; occupancy: string; location: string; version: number; findings_count: number; completeness: number };
type Evidence = { document_id: string; line: number; quote: string };
type Field = { key: string; label: string; value: string | number | null; state: string; evidence: Evidence[] };
type Document = { id?: string; name: string; text: string };
type Detail = Summary & { documents: Document[]; fields: Field[]; findings: { code: string; severity: string; title: string; detail: string }[]; events: { id: string; at: string; actor: string; action: string; note: string }[]; extractor: string; rules_version: string };
type Sample = { name: string; documents: Document[] };
const labels: Record<Status, string> = { new: 'To review', ready: 'Ready', needs_info: 'Needs information', referred: 'Referred' };
const money = (value: number | null) => value === null ? 'Unavailable' : new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(value);
const compactMoney = (value: number) => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', notation: 'compact', maximumFractionDigits: 1 }).format(value);
async function api<T>(path: string, body?: object): Promise<T> {
  const response = await fetch(`/api${path}`, body ? { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) } : undefined);
  if (!response.ok) {
    const error = await response.json().catch(() => ({}));
    throw new Error(typeof error.detail === 'string' ? error.detail : Array.isArray(error.detail) ? error.detail.map((item: { msg: string }) => item.msg).join('; ') : `Request failed (${response.status}).`);
  }
  return response.json();
}
function StatusTag({ status }: { status: Status }) { return <span className={`tag ${status}`}><i />{labels[status]}</span>; }

function App() {
  const [view, setView] = useState('queue');
  const [rows, setRows] = useState<Summary[]>([]);
  const [detail, setDetail] = useState<Detail | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState('all');
  const [tab, setTab] = useState('facts');
  const [source, setSource] = useState<Evidence | null>(null);
  const [reviewer, setReviewer] = useState('');
  const [note, setNote] = useState('');
  const [decision, setDecision] = useState<Status>('needs_info');
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState('');
  const [samples, setSamples] = useState<Sample[]>([]);
  const [documents, setDocuments] = useState<Document[]>([{ name: 'submission.txt', text: '' }]);
  const [dialogError, setDialogError] = useState('');
  const dialog = useRef<HTMLDialogElement>(null);
  const request = useRef(0);
  const selection = useRef('');
  async function refresh() { const result = await api<Summary[]>('/submissions'); setRows(result); return result; }
  async function select(id: string) {
    const current = ++request.current; selection.current = id;
    setError(''); setDetail(null); setSource(null); setNote(''); setNotice(''); setTab('facts'); setDecision('needs_info');
    try { const result = await api<Detail>(`/submissions/${id}`); if (current === request.current) setDetail(result); }
    catch (err) { if (current === request.current) setError((err as Error).message); }
  }
  useEffect(() => { refresh().then(result => { if (result.length) return select(result[0].id); }).catch(err => setError(err.message)).finally(() => setLoading(false)); }, []);
  const priorityOrder: Record<string, number> = { high: 0, medium: 1, low: 2 };
  const visible = rows.filter(row => (filter === 'all' || row.status === filter) && `${row.insured} ${row.broker} ${row.location}`.toLowerCase().includes(search.toLowerCase())).sort((left, right) => (priorityOrder[left.priority] ?? 3) - (priorityOrder[right.priority] ?? 3));
  const total = rows.reduce((sum, row) => sum + (row.tiv ?? 0), 0);
  const blockers = detail?.findings.some(finding => finding.severity === 'blocker');
  async function review(event: React.SubmitEvent<HTMLFormElement>) {
    event.preventDefault(); if (!detail) return; setBusy(true); setError(''); setNotice('');
    const id = detail.id;
    try {
      const result = await api<Detail>(`/submissions/${id}/review`, { status: decision, reviewer, note, version: detail.version });
      if (selection.current === id) { setDetail(result); setNote(''); setNotice('Review saved to the audit history.'); }
      await refresh();
    } catch (err) { setError((err as Error).message); } finally { setBusy(false); }
  }
  async function openIntake() {
    setDialogError(''); dialog.current?.showModal();
    try { setSamples(await api<Sample[]>('/samples')); } catch (err) { setDialogError((err as Error).message); }
  }
  async function create(event: React.SubmitEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setDialogError('');
    try {
      const result = await api<Detail>('/submissions', { documents: documents.map(({ name, text }) => ({ name, text })), extractor: 'deterministic' });
      await refresh(); await select(result.id); setView('queue'); dialog.current?.close();
      setDocuments([{ name: 'submission.txt', text: '' }]);
    } catch (err) { setDialogError((err as Error).message); } finally { setBusy(false); }
  }
  const sourceDoc = source ? detail?.documents.find(document => document.id === source.document_id) : null;
  return <div className="app">
    <aside className="rail"><a className="brand" href="#" onClick={event => { event.preventDefault(); setView('queue'); }}><span className="brand-mark">s<span> /</span></span><strong>sourceline<span>SUBMISSION WORKSPACE</span></strong></a><div className="rail-label">WORKSPACE</div><nav aria-label="Main navigation">{[['queue', '▤', 'Review queue'], ['portfolio', '◫', 'Portfolio'], ['brief', '↗', 'Project brief']].map(([key, icon, name]) => <button key={key} className={view === key ? 'active' : ''} onClick={() => setView(key)}><span aria-hidden="true">{icon}</span>{name}{key === 'queue' && <small>{rows.length}</small>}</button>)}</nav><div className="rail-bottom"><span className="status-dot" />LOCAL WORKSPACE<p>Commercial property<br />Evidence-led review</p><div className="avatar">SL</div><span>Independent project<br /><small>Synthetic records only</small></span></div></aside>
    <main><header className="topbar"><span>Technology portfolio <span className="slash">/</span> Commercial insurance</span><span className="demo-badge"><span />Synthetic data</span></header>
      <div className="content"><div className="page-title"><div><div className="eyebrow">COMMERCIAL PROPERTY · SUBMISSION OPERATIONS</div><h1>{view === 'queue' ? 'A clearer path to review.' : view === 'portfolio' ? 'The portfolio, in perspective.' : 'Built around the business.'}</h1><p>{view === 'queue' ? 'Reconcile the facts. Follow the evidence. Make a considered decision.' : view === 'portfolio' ? 'Known insured values and review progress across the submission book.' : 'An independent portfolio project built on a real commercial-property workflow.'}</p></div><button className="primary" onClick={openIntake}><span aria-hidden="true">＋</span> New submission</button></div>
      {error && <div className="alert" role="alert">{error} <button onClick={() => { setError(''); refresh().catch(err => setError(err.message)); if (selection.current) select(selection.current); }}>Refresh records</button></div>}
      {loading && <p role="status">Loading submissions…</p>}
      <section className="metrics" aria-label="Portfolio totals"><div><span>Submissions</span><strong>{rows.length.toString().padStart(2, '0')}</strong><small>In the workspace</small></div><div><span>Awaiting review</span><strong>{rows.filter(row => row.status === 'new').length.toString().padStart(2, '0')}</strong><small>New submissions</small></div><div><span>Known insured value</span><strong>{compactMoney(total)}</strong><small>{rows.filter(row => row.tiv === null).length} records without a usable value</small></div><div><span>Ready to hand off</span><strong>{rows.filter(row => row.status === 'ready').length.toString().padStart(2, '0')}</strong><small>Reviewer marked ready</small></div></section>
      {view === 'queue' && <><section className="queue panel"><div className="section-top"><div><h2>Submission queue <span>{visible.length}</span></h2><p>Highest priority first. Select a record to inspect its documents.</p></div><div className="filters"><input aria-label="Search submissions" type="search" placeholder="Search insured, broker, location" value={search} onChange={event => setSearch(event.target.value)} /><select aria-label="Filter review status" value={filter} onChange={event => setFilter(event.target.value)}><option value="all">All statuses</option>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select></div></div><div className="table-scroll"><table><thead><tr><th>Insured / broker</th><th>Occupancy</th><th>Insured value</th><th>Completeness</th><th>Status</th><th>Findings</th></tr></thead><tbody>{visible.map(row => <tr key={row.id} className={detail?.id === row.id ? 'selected' : ''}><td><button className="record-button" onClick={() => select(row.id)}>{row.insured || 'Unnamed submission'}<span>{row.broker || 'Broker missing'}</span></button></td><td>{row.occupancy || '—'}<small>{row.location}</small></td><td className="numeric">{money(row.tiv)}</td><td><div className="completeness"><progress value={row.completeness} max="100" aria-label={`${row.insured} completeness`} /><span>{row.completeness}%</span></div></td><td><StatusTag status={row.status} /></td><td><span className={`finding-count ${row.findings_count ? 'has-findings' : ''}`}>{row.findings_count}</span></td></tr>)}</tbody></table>{!loading && !visible.length && <p className="empty">No submissions match this view.</p>}</div></section>
      {detail && <section className="detail panel" aria-label="Selected submission"><div className="detail-heading"><div><div className="eyebrow">SUBMISSION DETAIL · {detail.id.slice(0, 8)}</div><h2>{detail.insured || 'Unnamed submission'}</h2><p>{detail.location || 'Location not provided'} <span>·</span> {detail.occupancy || 'Occupancy not provided'}</p></div><a className="secondary" href={`/api/submissions/${detail.id}/export`} download>Export record ↗</a></div><div className="detail-layout"><div className="detail-main"><div className="tabs" role="group" aria-label="Submission details">{[['facts', 'Facts & evidence'], ['documents', 'Documents'], ['history', 'Audit history']].map(([key, label]) => <button aria-pressed={tab === key} key={key} onClick={() => { setTab(key); setSource(null); }}>{label}{key === 'documents' && <span>{detail.documents.length}</span>}</button>)}</div>
      {tab === 'facts' && <div className="facts"><p className="helper">Source matched means a value was located in a document. It is not independent verification.</p><div className="field-grid">{detail.fields.map(field => <div className={`field field-${field.state}`} key={field.key}><div><span>{field.label}</span><small>{field.state === 'verified' ? 'Source matched' : field.state}</small></div><strong>{field.value === null ? 'Not available' : ['tiv', 'requested_limit', 'loss_total'].includes(field.key) ? money(Number(field.value)) : String(field.value)}</strong><div className="evidence-links">{field.evidence.map((evidence, index) => <button key={index} onClick={() => setSource(evidence)}>{detail.documents.find(document => document.id === evidence.document_id)?.name ?? 'Document'} · L{evidence.line} ↗</button>)}</div></div>)}</div>{sourceDoc && <div className="source-panel"><div><strong>{sourceDoc.name}</strong><button aria-label="Close source evidence" onClick={() => setSource(null)}>×</button></div><p>Source evidence · line {source?.line}</p><pre>{sourceDoc.text.split('\n').map((line, index) => <span className={source?.line === index + 1 ? 'highlight' : ''} key={index}><i>{index + 1}</i>{line || ' '}{'\n'}</span>)}</pre></div>}</div>}
      {tab === 'documents' && <div className="documents">{detail.documents.map((document, index) => <details key={document.id ?? index} open={index === 0}><summary>{document.name}</summary><pre>{document.text.split('\n').map((line, lineIndex) => <span key={lineIndex}><i>{lineIndex + 1}</i>{line || ' '}{'\n'}</span>)}</pre></details>)}</div>}
      {tab === 'history' && <ol className="timeline">{detail.events.map(event => <li key={event.id}><time>{new Date(event.at).toLocaleString()}</time><strong>{event.action.replaceAll('_', ' ')} <span>by {event.actor}</span></strong><p>{event.note}</p></li>)}{!detail.events.length && <p>No audit events yet.</p>}</ol>}
      </div><aside className="review-pane"><div className="review-title"><h3>Review findings</h3><span>{detail.findings.length}</span></div><p className="helper">Illustrative demo checks, not real underwriting rules.</p><div className="findings">{detail.findings.map(finding => <div className={`finding ${finding.severity}`} key={finding.code}><span>{finding.severity}</span><strong>{finding.title}</strong><p>{finding.detail}</p></div>)}{!detail.findings.length && <div className="clear-findings">✓ No rule findings<p>All required fields are source matched.</p></div>}</div><form onSubmit={review} className="review-form"><h3>Record your review</h3><label>Reviewer name<input required minLength={2} maxLength={80} value={reviewer} onChange={event => setReviewer(event.target.value)} placeholder="Your name" /></label><label>Disposition<select value={decision} onChange={event => setDecision(event.target.value as Status)}><option value="needs_info">Needs information</option><option value="referred">Refer for assessment</option><option value="ready" disabled={blockers}>Ready for handoff</option></select></label>{blockers && <p className="helper">Resolve missing, invalid or conflicting required facts before marking ready.</p>}<label>Review note<textarea required minLength={5} maxLength={2000} rows={3} value={note} onChange={event => setNote(event.target.value)} placeholder="Explain your decision and next steps…" /></label><button className="primary" disabled={busy || Boolean(blockers && decision === 'ready')}>{busy ? 'Saving…' : 'Save review'}</button><p className="helper">Self-declared reviewer identity for this local demo.</p>{notice && <p className="success" role="status">{notice}</p>}</form></aside></div></section>}
      </>}
      {view === 'portfolio' && <div className="portfolio"><section className="panel"><div className="section-top"><div><h2>Insured value by occupancy</h2><p>Sum of usable, nonconflicting values. USD.</p></div></div><div className="bars">{Object.entries(rows.reduce<Record<string, number>>((groups, row) => { const name = row.occupancy || 'Unspecified'; groups[name] = (groups[name] ?? 0) + (row.tiv ?? 0); return groups; }, {})).sort((a, b) => b[1] - a[1]).map(([name, value]) => <div key={name}><div><span>{name}</span><strong>{money(value)}</strong></div><progress value={value} max={total || 1} aria-label={`${name} share of known insured value`} /></div>)}</div></section><section className="panel"><div className="section-top"><div><h2>Review progress</h2><p>Human decisions across the book.</p></div></div><div className="status-list">{Object.entries(labels).map(([key, label]) => <div key={key}><StatusTag status={key as Status} /><strong aria-label={`${label} count`}>{rows.filter(row => row.status === key).length}</strong></div>)}</div><p className="portfolio-note">Submission values describe the synthetic intake book. They are not bound exposure, pricing or a prediction of loss.</p></section></div>}
      {view === 'brief' && <section className="panel brief"><div className="eyebrow">PROJECT BRIEF · COMMERCIAL PROPERTY</div><h2>Good technology starts with a real workflow.</h2><p>Broker submissions can contain missing or contradictory facts. Sourceline turns labeled documents into a structured review record, connects values to source lines, flags discrepancies and preserves a reviewer’s decision.</p><div className="brief-grid"><article><span>01 / BUSINESS FIT</span><h3>Evidence before decisions</h3><p>Commercial property insurers review broker submissions before anything is priced or bound. Contextualized data and an auditable decision trail are what make that review defensible.</p></article><article><span>02 / STACK FIT</span><h3>Python, React, TypeScript, SQL</h3><p>A typed API boundary, a React review workspace and relational persistence. FastAPI, Vite and local SQLite are this project’s implementation choices.</p></article><article><span>03 / CONTROLS</span><h3>Reviewable by design</h3><p>Required-field checks, explicit conflict handling, source references, persisted review notes and record versions demonstrate engineering, data quality and technology controls.</p></article></div><div className="brief-footer">Independent portfolio prototype. Synthetic data. No carrier affiliation, underwriting authority or production integration. See the repository research notes for domain sources and limitations.</div></section>}
      <footer>Sourceline <span>·</span> Independent portfolio prototype <span>·</span> Synthetic commercial-property data</footer></div>
    </main>
    <dialog ref={dialog} onCancel={() => setDialogError('')}><form onSubmit={create}><div className="dialog-heading"><div><div className="eyebrow">SUBMISSION INTAKE</div><h2>Start with the source.</h2></div><button type="button" className="close" onClick={() => dialog.current?.close()} aria-label="Close new submission">×</button></div><p>Choose a synthetic scenario or paste labeled document text. Exact labels keep every extracted fact traceable.</p><label>Sample scenario<select defaultValue="" onChange={event => { const sample = samples[Number(event.target.value)]; if (sample) setDocuments(sample.documents.map(document => ({ name: document.name, text: document.text }))); }}><option value="" disabled>Choose a scenario…</option>{samples.map((sample, index) => <option value={index} key={sample.name}>{sample.name}</option>)}</select></label>{documents.map((document, index) => <div className="document-input" key={index}><label>Document name<input required maxLength={120} value={document.name} onChange={event => setDocuments(current => current.map((item, i) => i === index ? { ...item, name: event.target.value } : item))} /></label><label>Document text<textarea required maxLength={50000} rows={7} value={document.text} onChange={event => setDocuments(current => current.map((item, i) => i === index ? { ...item, text: event.target.value } : item))} placeholder={'Insured: Example Manufacturing\nBroker: Example Brokerage\nLocation: Charlotte, NC\nOccupancy: Manufacturing\nTotal insured value: 5000000\nRequested limit: 3000000\nYear built: 2005\nSprinklered: Yes\nLoss count (5 years): 0\nTotal losses (5 years): 0'} /></label>{documents.length > 1 && <button className="text-button" type="button" onClick={() => setDocuments(current => current.filter((_, i) => i !== index))}>Remove document</button>}</div>)}<div className="intake-actions"><button type="button" className="secondary" disabled={documents.length >= 5} onClick={() => setDocuments(current => [...current, { name: `document-${current.length + 1}.txt`, text: '' }])}>＋ Add document</button><label className="upload">Import .txt<input type="file" accept=".txt,text/plain" onChange={async event => { const file = event.target.files?.[0]; if (!file) return; if (file.size > 150000 || documents.length >= 5) { setDialogError('Use a text file under 150 KB and at most five documents.'); return; } const text = await file.text(); if (text.length > 50000) { setDialogError('Each document must be under 50,000 characters.'); return; } setDocuments(current => current.length === 1 && !current[0].text ? [{ name: file.name, text }] : [...current, { name: file.name, text }]); event.target.value = ''; }} /></label></div>{dialogError && <div className="alert" role="alert">{dialogError}</div>}<div className="dialog-footer"><span>Local processing · No API key required</span><button className="primary" disabled={busy}>{busy ? 'Processing…' : 'Process submission →'}</button></div></form></dialog>
  </div>;
}

createRoot(document.getElementById('root')!).render(<App />);
